name: Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Check with ruff
        run: uv run ruff check src/ tests/

      - name: Check with mypy
        run: uv run mypy src/

      - name: Run tests
        run: uv run pytest tests/ -v -m "not e2e"
